apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: hello-spark
  namespace: default
spec:
  type: Java
  sparkVersion: 3.5.1
  mode: cluster
  image: hello-spark:vo
  mainClass: org.example.Main
  mainApplicationFile: local:///app/work/application.jar
  deps:
    packages:
      - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1
  sparkConf:
    "spark.driver.extraJavaOptions": "-Divy.cache.dir=/tmp -Divy.home=/tmp"
  driver:
    memory: 512m
    labels:
      version: 3.5.1
    serviceAccount: sparksubmit
  executor:
    memory: 512m
    instances: 3
    labels:
      version: 3.5.1